version: '3'

services:
  mock-oauth2-server:
    image: ghcr.io/navikt/mock-oauth2-server:0.3.4
    ports:
      - 8888:8080
  spanner:
    depends_on:
      - mock-oauth2-server
    restart: always
    build: .
    ports:
      - 8080:8080
    environment:
      AZURE_APP_WELL_KNOWN_URL: http://mock-oauth2-server:8080/default/.well-known/openid-configuration
      AZURE_APP_CLIENT_ID: foo
      AZURE_APP_CLIENT_SECRET: bar
      ISSUER: baz
      ACCEPTED_AUDIENCE: quoz
      SPLEIS_CLIENT_ID: foobar
      AUTHORIZATION_URL: http://localhost:8888/default/authorize
      KTOR_ENV: local
      SPLEIS_API_URL: http://dummy
  audit.nais:
    image: balabit/syslog-ng:latest
    volumes:
      - ${PWD}/audit-test.conf:/etc/syslog-ng/syslog-ng.conf