apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: spanner
  namespace: tbd
  labels:
    team: tbd
spec:
  image: {{image}}
  port: 8080
  ingresses:
    - https://spanner.intern.nav.no
  liveness:
    failureThreshold: 10
    initialDelay: 20
    path: isalive
    timeout: 1
  readiness:
    initialDelay: 20
    path: isready
    timeout: 1
  replicas:
    cpuThresholdPercentage: 90
    max: 1
    min: 1
  resources:
    limits:
      cpu: 2000m
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 128Mi
  azure:
    application:
      enabled: true
      claims:
        groups:
          - id: "f787f900-6697-440d-a086-d5bb56e26a9c"
  webproxy: true
  secureLogs:
    enabled: true
  env:
    - name: LOCAL
      value: "false"
    - name: SPLEIS_CLIENT_ID
      value: api://prod-fss.tbd.spleis/.default
    - name: HTTP_PORT
      value: "8080"
    - name: HOST
      value: spanner.nais.adeo.no
